INSERT INTO FIFTEENGG.QUEUETYPE (QUEUEID, QUEUENAME) VALUES (420, '솔로랭크');
INSERT INTO FIFTEENGG.QUEUETYPE (QUEUEID, QUEUENAME) VALUES (430, '일반게임');
INSERT INTO FIFTEENGG.QUEUETYPE (QUEUEID, QUEUENAME) VALUES (440, '자유랭크');
INSERT INTO FIFTEENGG.QUEUETYPE (QUEUEID, QUEUENAME) VALUES (450, '칼바');
INSERT INTO FIFTEENGG.QUEUETYPE (QUEUEID, QUEUENAME) VALUES (900, '우루프모드');